# -*- coding: utf-8 -*-
"""src/data_stream.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJsxxiveqhXomCidWaV_kJlg_p4l2vwV
"""

import time
import os
import shutil

SOURCE_DIR = 'data/source/'
STREAM_DIR = 'data/stream/'

def simulate_data_stream():
    # Move files from source to stream directory one by one to simulate streaming
    for file_name in os.listdir(SOURCE_DIR):
        if file_name.endswith('.fits'):
            shutil.move(os.path.join(SOURCE_DIR, file_name), os.path.join(STREAM_DIR, file_name))
            print(f"Streaming {file_name}")
            time.sleep(1)  # Simulate delay between data arrivals

if __name__ == "__main__":
    simulate_data_stream()