# -*- coding: utf-8 -*-
"""tests/test_sonification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJsxxiveqhXomCidWaV_kJlg_p4l2vwV
"""

import unittest
from src.sonification import spectrum_to_sound

class TestSonification(unittest.TestCase):

    def test_spectrum_to_sound(self):
        wavelength = [4000, 5000, 6000, 7000]
        flux = [1, 0.8, 0.6, 0.4]
        sound_wave = spectrum_to_sound(wavelength, flux)
        self.assertEqual(len(sound_wave), 44100)  # Check if the sound wave has the correct length

if __name__ == '__main__':
    unittest.main()